<?xml version="1.0"?>
<ArrayOfProjectSuo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProjectSuo>
    <DiagramName>Siemens_SimaticIT_MS_BasicDataManageFBLib.dm</DiagramName>
    <FileName>BasicDataManageFBLib.MSModel</FileName>
    <Artifacts>
      <ArtifactSuo>
        <X>838.8</X>
        <Y>265.6</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.DataModel.DataItemCategoryEntity</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>66.400000000000091</X>
        <Y>59.200000000000017</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.DataModel.DataItemEntity</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>914.59999999999991</X>
        <Y>137.99999999999997</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemCategoryAddCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>559</X>
        <Y>9</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemCategoryUpdateCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>788</X>
        <Y>9</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemCategoryDelCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>684</X>
        <Y>103</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemAddCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>312</X>
        <Y>19</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemUpdateCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>897.59999999999991</X>
        <Y>283.59999999999997</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DataItemDelCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>991</X>
        <Y>8</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.GetTreeDataCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1148</X>
        <Y>8</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Types.GetTreeList</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1052.6</X>
        <Y>263.20000000000005</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.GetFactoryModelCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>true</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1276</X>
        <Y>13</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Types.FactoryModelType</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>17</X>
        <Y>394</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.DataModel.AppModelEntity</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>127</X>
        <Y>383</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.DataModel.AppRolesConfiEntity</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>282</X>
        <Y>380</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.DataModel.AppUsersEntity</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>880</X>
        <Y>369</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.AddAppModelCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1025</X>
        <Y>368</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.DelAppModelCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1177</X>
        <Y>369</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.UpdateAppModelCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1327</X>
        <Y>252</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Types.RoleModelType</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1460</X>
        <Y>13</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.SaveAppRolesConfiCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1669</X>
        <Y>8</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.UpdateAppPasswordCmd</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>419</X>
        <Y>373</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.ResetAppPwdCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>586</X>
        <Y>370</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Types.UserBtnListType</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>731</X>
        <Y>371</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Types.UserPageListType</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>1363</X>
        <Y>367</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.GetAppUserRolesCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>577</X>
        <Y>451</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.GetUAUsersCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>true</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>719</X>
        <Y>452</Y>
        <FullName>Siemens.SimaticIT.MasterData.BasicDataManageFBLib.MSModel.Commands.UpdateAppUserCmd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
    </Artifacts>
  </ProjectSuo>
</ArrayOfProjectSuo>