//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ALP.Application.Service.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MES2SAPSoap", Namespace="http://tempuri.org/")]
    public partial class MES2SAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Post_PushPurchaseInWhInfo_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Post_PushPurchaseInWhInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Post_PushJobWorkingInfo_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Post_PushJobWorkingInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MES2SAP() {
            this.Url = global::ALP.Application.Service.Properties.Settings.Default.ALP_Application_Service_WebReference_MES2SAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Post_PushPurchaseInWhInfo_TestCompletedEventHandler Post_PushPurchaseInWhInfo_TestCompleted;
        
        /// <remarks/>
        public event Post_PushPurchaseInWhInfoCompletedEventHandler Post_PushPurchaseInWhInfoCompleted;
        
        /// <remarks/>
        public event Post_PushJobWorkingInfo_TestCompletedEventHandler Post_PushJobWorkingInfo_TestCompleted;
        
        /// <remarks/>
        public event Post_PushJobWorkingInfoCompletedEventHandler Post_PushJobWorkingInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Post_PushPurchaseInWhInfo_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Post_PushPurchaseInWhInfo_Test() {
            object[] results = this.Invoke("Post_PushPurchaseInWhInfo_Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Post_PushPurchaseInWhInfo_TestAsync() {
            this.Post_PushPurchaseInWhInfo_TestAsync(null);
        }
        
        /// <remarks/>
        public void Post_PushPurchaseInWhInfo_TestAsync(object userState) {
            if ((this.Post_PushPurchaseInWhInfo_TestOperationCompleted == null)) {
                this.Post_PushPurchaseInWhInfo_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPost_PushPurchaseInWhInfo_TestOperationCompleted);
            }
            this.InvokeAsync("Post_PushPurchaseInWhInfo_Test", new object[0], this.Post_PushPurchaseInWhInfo_TestOperationCompleted, userState);
        }
        
        private void OnPost_PushPurchaseInWhInfo_TestOperationCompleted(object arg) {
            if ((this.Post_PushPurchaseInWhInfo_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Post_PushPurchaseInWhInfo_TestCompleted(this, new Post_PushPurchaseInWhInfo_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Post_PushPurchaseInWhInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Post_PushPurchaseInWhInfo(string sBatchCode, PushPurchaseInWhEntity[] lstJwInfo) {
            object[] results = this.Invoke("Post_PushPurchaseInWhInfo", new object[] {
                        sBatchCode,
                        lstJwInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Post_PushPurchaseInWhInfoAsync(string sBatchCode, PushPurchaseInWhEntity[] lstJwInfo) {
            this.Post_PushPurchaseInWhInfoAsync(sBatchCode, lstJwInfo, null);
        }
        
        /// <remarks/>
        public void Post_PushPurchaseInWhInfoAsync(string sBatchCode, PushPurchaseInWhEntity[] lstJwInfo, object userState) {
            if ((this.Post_PushPurchaseInWhInfoOperationCompleted == null)) {
                this.Post_PushPurchaseInWhInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPost_PushPurchaseInWhInfoOperationCompleted);
            }
            this.InvokeAsync("Post_PushPurchaseInWhInfo", new object[] {
                        sBatchCode,
                        lstJwInfo}, this.Post_PushPurchaseInWhInfoOperationCompleted, userState);
        }
        
        private void OnPost_PushPurchaseInWhInfoOperationCompleted(object arg) {
            if ((this.Post_PushPurchaseInWhInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Post_PushPurchaseInWhInfoCompleted(this, new Post_PushPurchaseInWhInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Post_PushJobWorkingInfo_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Post_PushJobWorkingInfo_Test() {
            object[] results = this.Invoke("Post_PushJobWorkingInfo_Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Post_PushJobWorkingInfo_TestAsync() {
            this.Post_PushJobWorkingInfo_TestAsync(null);
        }
        
        /// <remarks/>
        public void Post_PushJobWorkingInfo_TestAsync(object userState) {
            if ((this.Post_PushJobWorkingInfo_TestOperationCompleted == null)) {
                this.Post_PushJobWorkingInfo_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPost_PushJobWorkingInfo_TestOperationCompleted);
            }
            this.InvokeAsync("Post_PushJobWorkingInfo_Test", new object[0], this.Post_PushJobWorkingInfo_TestOperationCompleted, userState);
        }
        
        private void OnPost_PushJobWorkingInfo_TestOperationCompleted(object arg) {
            if ((this.Post_PushJobWorkingInfo_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Post_PushJobWorkingInfo_TestCompleted(this, new Post_PushJobWorkingInfo_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Post_PushJobWorkingInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Post_PushJobWorkingInfo(string sBatchCode, PushJobWorkingInfoEntity[] lstJwInfo) {
            object[] results = this.Invoke("Post_PushJobWorkingInfo", new object[] {
                        sBatchCode,
                        lstJwInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Post_PushJobWorkingInfoAsync(string sBatchCode, PushJobWorkingInfoEntity[] lstJwInfo) {
            this.Post_PushJobWorkingInfoAsync(sBatchCode, lstJwInfo, null);
        }
        
        /// <remarks/>
        public void Post_PushJobWorkingInfoAsync(string sBatchCode, PushJobWorkingInfoEntity[] lstJwInfo, object userState) {
            if ((this.Post_PushJobWorkingInfoOperationCompleted == null)) {
                this.Post_PushJobWorkingInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPost_PushJobWorkingInfoOperationCompleted);
            }
            this.InvokeAsync("Post_PushJobWorkingInfo", new object[] {
                        sBatchCode,
                        lstJwInfo}, this.Post_PushJobWorkingInfoOperationCompleted, userState);
        }
        
        private void OnPost_PushJobWorkingInfoOperationCompleted(object arg) {
            if ((this.Post_PushJobWorkingInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Post_PushJobWorkingInfoCompleted(this, new Post_PushJobWorkingInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PushPurchaseInWhEntity {
        
        private string aPPLYBATCHField;
        
        private string rEPORTCODEField;
        
        private string sNUMBERField;
        
        private string pORDERField;
        
        private string wORDERCODEField;
        
        private int rSPOSField;
        
        private string mACODEField;
        
        private string mADESCField;
        
        private int mAQUANTITYField;
        
        /// <remarks/>
        public string APPLYBATCH {
            get {
                return this.aPPLYBATCHField;
            }
            set {
                this.aPPLYBATCHField = value;
            }
        }
        
        /// <remarks/>
        public string REPORTCODE {
            get {
                return this.rEPORTCODEField;
            }
            set {
                this.rEPORTCODEField = value;
            }
        }
        
        /// <remarks/>
        public string SNUMBER {
            get {
                return this.sNUMBERField;
            }
            set {
                this.sNUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string PORDER {
            get {
                return this.pORDERField;
            }
            set {
                this.pORDERField = value;
            }
        }
        
        /// <remarks/>
        public string WORDERCODE {
            get {
                return this.wORDERCODEField;
            }
            set {
                this.wORDERCODEField = value;
            }
        }
        
        /// <remarks/>
        public int RSPOS {
            get {
                return this.rSPOSField;
            }
            set {
                this.rSPOSField = value;
            }
        }
        
        /// <remarks/>
        public string MACODE {
            get {
                return this.mACODEField;
            }
            set {
                this.mACODEField = value;
            }
        }
        
        /// <remarks/>
        public string MADESC {
            get {
                return this.mADESCField;
            }
            set {
                this.mADESCField = value;
            }
        }
        
        /// <remarks/>
        public int MAQUANTITY {
            get {
                return this.mAQUANTITYField;
            }
            set {
                this.mAQUANTITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PushJobWorkingInfoEntity {
        
        private string aPPLYBATCHField;
        
        private string rEPORTCODEField;
        
        private string sNUMBERField;
        
        private string pORDERField;
        
        private string mACODEField;
        
        private int mAQUANTITYField;
        
        private string aCCOUNTDATEField;
        
        private int iSPARTField;
        
        /// <remarks/>
        public string APPLYBATCH {
            get {
                return this.aPPLYBATCHField;
            }
            set {
                this.aPPLYBATCHField = value;
            }
        }
        
        /// <remarks/>
        public string REPORTCODE {
            get {
                return this.rEPORTCODEField;
            }
            set {
                this.rEPORTCODEField = value;
            }
        }
        
        /// <remarks/>
        public string SNUMBER {
            get {
                return this.sNUMBERField;
            }
            set {
                this.sNUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string PORDER {
            get {
                return this.pORDERField;
            }
            set {
                this.pORDERField = value;
            }
        }
        
        /// <remarks/>
        public string MACODE {
            get {
                return this.mACODEField;
            }
            set {
                this.mACODEField = value;
            }
        }
        
        /// <remarks/>
        public int MAQUANTITY {
            get {
                return this.mAQUANTITYField;
            }
            set {
                this.mAQUANTITYField = value;
            }
        }
        
        /// <remarks/>
        public string ACCOUNTDATE {
            get {
                return this.aCCOUNTDATEField;
            }
            set {
                this.aCCOUNTDATEField = value;
            }
        }
        
        /// <remarks/>
        public int ISPART {
            get {
                return this.iSPARTField;
            }
            set {
                this.iSPARTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Post_PushPurchaseInWhInfo_TestCompletedEventHandler(object sender, Post_PushPurchaseInWhInfo_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Post_PushPurchaseInWhInfo_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Post_PushPurchaseInWhInfo_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Post_PushPurchaseInWhInfoCompletedEventHandler(object sender, Post_PushPurchaseInWhInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Post_PushPurchaseInWhInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Post_PushPurchaseInWhInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Post_PushJobWorkingInfo_TestCompletedEventHandler(object sender, Post_PushJobWorkingInfo_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Post_PushJobWorkingInfo_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Post_PushJobWorkingInfo_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Post_PushJobWorkingInfoCompletedEventHandler(object sender, Post_PushJobWorkingInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Post_PushJobWorkingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Post_PushJobWorkingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591