<?xml version="1.0"?>
<ArrayOfProjectSuo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProjectSuo>
    <DiagramName>Siemens_SimaticIT_MS_ButtonAuthFBLib.dm</DiagramName>
    <FileName>ButtonAuthFBLib.MSModel</FileName>
    <Artifacts>
      <ArtifactSuo>
        <X>43.399999999999864</X>
        <Y>326.6</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderDel</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>217.8</X>
        <Y>224.2</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderPublish</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>true</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>184.2</X>
        <Y>12.999999999999943</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderDelWO</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>11.39999999999992</X>
        <Y>119.39999999999998</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderEditWO</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>604.20000000000027</X>
        <Y>122.59999999999997</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderImportWO</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>421.7999999999999</X>
        <Y>230.60000000000008</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderAddPick</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>208.99999999999983</X>
        <Y>333.8</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderDemand</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>605.00000000000023</X>
        <Y>348.2</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderEditPlan</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>13.000000000000071</X>
        <Y>7.4000000000000057</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderDel</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>379.4</X>
        <Y>17.800000000000011</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderEdit</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>565.00000000000011</X>
        <Y>17.799999999999997</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderEditMaterial</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>209</X>
        <Y>116.19999999999999</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderFrozen</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>402.59999999999997</X>
        <Y>121.00000000000003</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderImportPrd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>29.800000000000011</X>
        <Y>217</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderLoad</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>601.00000000000023</X>
        <Y>234.60000000000008</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderAddSupple</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>400.2</X>
        <Y>334.6</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderEditBom</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>39.400000000000034</X>
        <Y>429.80000000000007</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderEditProcess</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>242.60000000000002</X>
        <Y>441.00000000000011</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderEditQuality</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>424.2000000000001</X>
        <Y>443.40000000000003</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>797.00000000000023</X>
        <Y>336.20000000000005</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageOutWhs</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>827.4</X>
        <Y>226.60000000000002</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageMove</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>822.60000000000014</X>
        <Y>133.8</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageMove2</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>666.59999999999991</X>
        <Y>459.39999999999986</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageAdjust</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>true</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>37.0000000000001</X>
        <Y>533</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ReworkDel</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>807.40000000000009</X>
        <Y>18.600000000000023</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderTransfer</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseMaterialAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseMaterialEdit</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseMaterialDelete</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMEdit</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMDelete</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMAddDetail</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMEditDetail</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMDeleteDetail</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMCopy</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.BaseBOMPaste</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageBackup</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>765.80000000000018</X>
        <Y>253.00000000000003</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ReworkQualityConfirm</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>823.40000000000009</X>
        <Y>376.20000000000005</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.RawMaterialStockManageOutWhs2</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>true</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>154.6</X>
        <Y>540.19999999999982</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductionOrderSapPublish</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>352.2</X>
        <Y>542.59999999999991</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.PurchaseManageAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>533.00000000000011</X>
        <Y>549</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.PurchaseManageEdit</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>697.8</X>
        <Y>557.8</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.PurchaseManageDelete</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>871.40000000000009</X>
        <Y>533.8</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.PurchaseManageDeleteDetail</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ReceiptNoticeAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>233.00000000000006</X>
        <Y>9</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ReceiptNoticeEdit</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>543.40000000000009</X>
        <Y>12.200000000000046</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ReceiptNoticeDelete</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductStockManageInWhs</FullName>
        <IsExpandedA>true</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductStockManageAdjust</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.ProductDispatchAdd</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.WorkOrderFinishCase</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
      <ArtifactSuo>
        <X>5</X>
        <Y>5</Y>
        <FullName>Siemens.SimaticIT.MasterData.ButtonAuthFBLib.MSModel.Commands.OwnProductFinishCase</FullName>
        <IsExpandedA>false</IsExpandedA>
        <IsExpandedB>false</IsExpandedB>
        <IsExpandedC>false</IsExpandedC>
      </ArtifactSuo>
    </Artifacts>
  </ProjectSuo>
</ArrayOfProjectSuo>